apiVersion: v1
kind: Service
metadata:
  name: go-hello-cloud-code
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 9090
      targetPort: 8080
  selector:
    app: go-hello-cloud-code
